### PR TITLE
➕Adding Tensorflow dependencies

### PR DESCRIPTION
**Pull request by Axelvel**
Added all the dependencies necessary to run TensorFlow on macOS and Windows/Linux:

## What has been done
- Installed `tensorflow` to create neural networks for our deep reinforcement learning algorithm
- Split the requirements.txt file into 2: one for Windows/Linux and one for macOS to avoid dependencies conflicts
- Installed the right tensorflow depencies for macOS (`tensorflow-macos`, ` tensorflow-deps`, `tensorflow-metal`)
- Modified the `make update` and `make export` commands to automatically use the right requirements file

## What can be done in the future
- Create a common requirements.txt and put the platform exclusive dependencies in additional files

## Coverage
|Name  |  Stmts |  Miss | Cover | Missing
|-|-|-|-|-|
|TOTAL |    270  |    0 |  100%|

### CODE REVIEW

**Review by galyfray — CHANGES_REQUESTED** [review]
Some commits from the original PR seems to be missing here.

**Comment by galyfray** [comment]
Here are the two missing commits :
`dc07e0c18cbc61c3b90038af9ec4b1f335ffb214`
`11449ed9660f5231c726d19e54356408cb52f71f`

**Comment by Axelvel** [comment]
> Here are the two missing commits :
> `dc07e0c18cbc61c3b90038af9ec4b1f335ffb214`
> `11449ed9660f5231c726d19e54356408cb52f71f`

Added the 3 missing commits (`60cd0d82c141a051dd46f9455333f156e4bc3c5d` was forgotten as well

**Review by galyfray — DISMISSED** [review]
This PR seems good to me.

**Review by Nexowo — DISMISSED** [review]
Seems all good

**Review by galyfray — APPROVED** [review]
yup

**Review by m-aspro — APPROVED** [review]
Everything seems good to me
Good job @Axelvel

**Review by Nexowo — APPROVED** [review]

**Pull request merged**
